randomize();
show_debug_overlay(true);
//snd = SonusIndexAdd("fanfare60.wav", false, true);
//SonusGroupAddSound(snd, "ui_popup");
snd = SonusIndexAdd("ui_menu_popup_message_04.ogg");
SonusGroupAddSound(snd, "ui_popup");
snd = SonusIndexAdd("ui_menu_popup_message_022.wav");
SonusGroupAddSound(snd, "ui_popup");
group = SonusGroupGet("ui_popup").SetPitchRange(1,2);
snd = SonusIndexGetRandom("ui_popup");